server:
  port: 8080
  servlet:
    context-path: /dataReplenish
#db
spring:
  datasource:
    first:
      username: root
      password: ********
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/test_database?useUnicode=true&characterEncoding=UTF-8&useOldAliasMetadataBehavior=true&autoReconnect=true
#log
logging:
  level:
    com:
      alibaba: DEBUG
      ibatis: DEBUG
      lcl.datareplenish: INFO
    org:
      mybatis: DEBUG
      springframework.boot.autoconfigure: ERROR

  file:
    name: /Users/liuchanglin/IdeaProjects/logs/dataReplenish.log
